export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const POST_USER_DATA_REQUEST = 'POST_USER_DATA_REQUEST';
export const DELETE_USER_DATA_REQUEST = 'DELETE_USER_DATA_REQUEST';

export const GET_BOOK_DATA_REQUEST = 'GET_BOOK_DATA_REQUEST';
export const GET_BOOK_DATA_SUCCESS = 'GET_BOOK_DATA_SUCCESS';
export const POST_BOOK_DATA_REQUEST = 'POST_BOOK_DATA_REQUEST';
export const DELETE_BOOK_DATA_REQUEST = 'DELETE_BOOK_DATA_REQUEST';